### ISSUE TITLE
Online players bugged

### ISSUE THREAD

**Issue by TheCrunchy** [Casimir255/SeamlessClientPlugin#2]
Players seem to be bugged when using the seamless and crossing instances, not showing up in f3, showing as hostile colour in the chat while in same faction. Relog fixes it

![nexus1](https://user-images.githubusercontent.com/13859025/112004124-6d5a2680-8b19-11eb-9d0e-aa07c0c019ac.png)
![nexus2](https://user-images.githubusercontent.com/13859025/112004130-6df2bd00-8b19-11eb-95f5-6553041a994e.PNG)
![nexus3](https://user-images.githubusercontent.com/13859025/112004132-6df2bd00-8b19-11eb-90ff-c61a17ed5171.PNG)
![nexus4](https://user-images.githubusercontent.com/13859025/112004575-d5107180-8b19-11eb-9011-85b07e555dbd.PNG)

**Comment by Casimir255** [comment]
Please attach your log file

**Comment by TheCrunchy** [comment]
[VRageRender-DirectX11_20210322_134658975.log](https://github.com/Casimir255/SeamlessClientPlugin/files/6184135/VRageRender-DirectX11_20210322_134658975.log)

**Comment by TheCrunchy** [comment]
[SpaceEngineers_20210322_134657598.log](https://github.com/Casimir255/SeamlessClientPlugin/files/6184139/SpaceEngineers_20210322_134657598.log)

**Comment by epa-shinobi2** [comment]
Confirm on this also -- new effect (Shinobi from [EPA]):
This behavior seems to also impact the Quantum Datacore collection script which will detect player suit (mySkinningComponent) in the KOTH zone, which will require that players with Seamless Plugin re-log into the instance in order for the script to account for their presence.

I will collect logs to send, and screens and update this posting.
discord.gg/epa-community

**Comment by Casimir255** [comment]
So i just tested the online player stuff and didn't have any problems. (My F3 menu matched servers F3 menu)

Is this overtime or instant?

**Comment by Casimir255** [comment]
Alright, so its my assumption that new players don't register

**Comment by Allen-Wrench** [comment]
yeah, people who are in the server when you connect will show up, but after that any players that connect will not show as connected. the !tags command will accurately show connected players, i assume because its a server-side command, but it might shed some light onto the problem.

**Comment by epa-shinobi2** [comment]
**UPDATE**: It's cosmetic. The displayed %s are simply showing what it knows locally -- but a simple re-log (F5) fixes it, as likely is that's when your client has a fresh copy of the script being used in that KOTH tracker (?)

It's minor -- but as it's cosmetic, I don't think it's actually effecting any real timers.
